# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Azure App Service - Node.js

on:
  push:
    branches:
      - main
    paths:
    - 'app/**'
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
    paths:
    - 'app/**'

  workflow_dispatch:

env:
  APP_NAME: economy-simplified
  APP_NAME_BETA: economy-simplified-beta
  APP_URL: https://economy-simplified.azurewebsites.net
  APP_URL_BETA: https://economy-simplified-beta.azurewebsites.net
  APP_DIR: app

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
        working-directory: ${{ env.APP_DIR }}

      # Zip artifacts to speed things up
      - name: Zip artifact for deployment
        run: |
          zip release.zip ./* -qr -x "node_modules/*" "dist/*"
        # zip release-app.zip ./${{ env.APP_DIR }}* -qr -x "node_modules/*" "dist/*"
        # We exclude node_modules and dist because the Azure Oryx/Kudu deploy runs npm install and rebuilds everything anyway...
        # If we zip them we just increase the size of the zip file and it's not needed

      - name: Upload repo artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: release.zip

      #- name: Upload app artifact for deployment job
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: node-app
      #    path: release-app.zip

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.pull_request.merged == false && github.ref != 'refs/heads/main'
    environment:
      name: 'Staging'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: |
          ls -l
          unzip -q release.zip
          rm release.zip

      - name: Display contents of dir
        run: |
          echo "root dir"
          ls -l
          echo ""
          echo "${{ env.APP_DIR }} dir"
          ls -l ${{ env.APP_DIR }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME_BETA }}
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4D74D769041F42B3B3ACFA629E0C9558 }}
          package: ${{ env.APP_DIR }}
      
      - name: Comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.number }}
          body: |
            Deployed at [Staging URL][1]

            [1]: ${{ env.APP_URL_BETA }}

  deploy-production:
    runs-on: ubuntu-latest
    needs: build
    #if: github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
    if: github.ref == 'refs/heads/main'
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: |
          ls -l
          unzip -q release.zip
          rm release.zip

      - name: Display contents of dir
        run: |
          echo "root dir"
          ls -l
          echo ""
          echo "${{ env.APP_DIR }} dir"
          ls -l ${{ env.APP_DIR }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3A2C0B3F9CEA4225BAB656C1273E4BD5 }}
          package: ${{ env.APP_DIR }}
